Update main.yml
Need to see if secrets working

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,6 +29,8 @@ jobs:
         with:
           name: trivy-results
           path: trivy-results.sarif
+          #Part 2 is Below
+          
   image_scan:
     name: Build Image and Run Image Scan
     runs-on: ubuntu-latest
@@ -41,6 +43,16 @@ jobs:
 
       - name: Build Docker Image
         run: docker build -f Dockerfile -t pygoat_app:latest .
+
+      - name: Verify Secrets
+        run: |
+          [ -n "${{ secrets.REPO_USER }}" ] || { echo "Missing REPO_USER secret"; exit 1; }
+          [ -n "${{ secrets.REPO_PWD }}" ]  || { echo "Missing REPO_PWD secret"; exit 1; }
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.REPO_USER }}
+          password: ${{ secrets.REPO_PWD }}
 
       - name: Docker Scout Scan
         uses: docker/scout-action@v1.15.0
